# Generated by Django 4.0.5 on 2022-09-07 17:59

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('palapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observ',
            field=models.TextField(default='', null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='fecha_inicon',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Inicio de Contrato'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='codagente',
            field=models.CharField(default='', max_length=20, verbose_name='Cod.Agente Inmobiliario'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='fecha_cese',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fecha de Cese'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='tramites',
            name='fec_prox',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 17, 59, 2, 803003, tzinfo=utc), verbose_name='Fecha proximo trámite'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ruc',
            field=models.CharField(default='', max_length=11, null=True, verbose_name='RUC'),
        ),
    ]
