# Generated by Django 4.0.5 on 2022-09-07 18:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palapp', '0003_cliente_observ_inmobiliaria_fecha_inicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmobiliaria',
            name='usuar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tramites',
            name='fec_prox',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 18, 15, 25, 468387, tzinfo=utc), verbose_name='Fecha proximo trámite'),
        ),
    ]
