# Generated by Django 4.0.5 on 2022-09-10 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palapp', '0004_inmobiliaria_usuar_alter_tramites_fec_prox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmobiliaria',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_crea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jefe',
            name='usuario_crea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terreno',
            name='usuario_crea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tramites',
            name='usuario_crea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='id_usuario_jefe',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tramites',
            name='fec_prox',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha proximo trámite'),
        ),
    ]
