# Generated by Django 4.0.5 on 2022-09-11 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palapp', '0005_remove_inmobiliaria_usuario_cliente_usuario_crea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ressoc', models.CharField(max_length=50, null=True, verbose_name='Razón Social')),
                ('ruc', models.CharField(default='', max_length=11, null=True, verbose_name='RUC')),
                ('direccion', models.TextField(default='AREQUIPA', verbose_name='Dirección Casa')),
                ('correo', models.EmailField(default='@', max_length=254, verbose_name='eMail')),
                ('telfij', models.CharField(default='', max_length=15, verbose_name='Teléfono Fijo')),
                ('cel1', models.CharField(default='', max_length=15, verbose_name='Celular 1')),
                ('cel2', models.CharField(default='', max_length=15, verbose_name='Celular 2')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecact', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('usuario_crea', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Coordinador')),
            ],
        ),
        migrations.AlterModelOptions(
            name='jefe',
            options={'verbose_name': 'encargado', 'verbose_name_plural': 'encargados'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palapp.vendedor', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='inmobiliaria',
            name='usuar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AlterField(
            model_name='jefe',
            name='inmobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palapp.inmobiliaria', verbose_name='Inmobiliaria'),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palapp.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palapp.vendedor', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='tramites',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='palapp.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='tramites',
            name='terreno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='palapp.terreno', verbose_name='Terreno'),
        ),
        migrations.AlterField(
            model_name='tramites',
            name='vendedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='palapp.vendedor', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='id_usuario_jefe',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Coordinador'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='jefe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='palapp.jefe', verbose_name='Nombre Coordinador'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('banco', models.TextField(max_length=40, verbose_name='Banco')),
                ('condvta', models.CharField(choices=[('C', 'Contado'), ('B', 'Financiamiento Banco'), ('P', 'FInanciamiento Propio')], max_length=1, verbose_name='Condición Venta')),
                ('nro_cont', models.TextField(verbose_name='Número de Contrato')),
                ('fec_con', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Contrato')),
                ('preciod', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='P.Venta US$')),
                ('precios', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='P.Venta S/')),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comisión %')),
                ('observ', models.TextField(verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecact', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='palapp.cliente', verbose_name='Cliente')),
                ('notaria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='palapp.notaria', verbose_name='Notaria')),
                ('terreno', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='palapp.terreno', verbose_name='Terreno')),
                ('usuario_crea', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='palapp.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuota', models.IntegerField(default=1, verbose_name='Cuota No.')),
                ('fec_vcto', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Vencimiento')),
                ('fec_pago', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Pago')),
                ('preciod', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pago US$')),
                ('precios', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pago S/')),
                ('gastosd', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Gastos US$')),
                ('gastoss', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Gastos S/')),
                ('nrooper', models.CharField(max_length=30, verbose_name='Numero Operación')),
                ('banco', models.CharField(max_length=40, verbose_name='Banco')),
                ('observ', models.TextField(verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Cancelado')], default='P', max_length=1, verbose_name='Estado')),
                ('foto_vouc', models.ImageField(upload_to='', verbose_name='Foto Voucher')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecact', models.DateTimeField(blank=True, null=True)),
                ('usuario_crea', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='palapp.cliente', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
            },
        ),
    ]
