# Generated by Django 4.0.5 on 2022-09-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palapp', '0006_notaria_alter_jefe_options_alter_cliente_vendedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='efectivo',
            field=models.BooleanField(default=1, verbose_name='Efectivo?'),
            preserve_default=False,
        ),
    ]
