# Generated by Django 4.0.5 on 2022-09-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palapp', '0008_rename_ressoc_notaria_rassoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaria',
            name='cel2',
            field=models.CharField(default='', max_length=15, null=True, verbose_name='Celular 2'),
        ),
        migrations.AlterField(
            model_name='notaria',
            name='direccion',
            field=models.TextField(default='AREQUIPA', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='notaria',
            name='telfij',
            field=models.CharField(default='', max_length=15, null=True, verbose_name='Teléfono Fijo'),
        ),
    ]
