# Generated by Django 4.0.5 on 2022-09-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palapp', '0009_alter_notaria_cel2_alter_notaria_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cel2',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Celular 2'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celcon',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Numero contacto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='directra',
            field=models.TextField(blank=True, default='AREQUIPA', verbose_name='Dirección Trabajo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observ',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='percon',
            field=models.TextField(blank=True, default='', verbose_name='Persona de contacto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telfij',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Teléfono Fijo'),
        ),
        migrations.AlterField(
            model_name='jefe',
            name='cel2',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Celular 2'),
        ),
        migrations.AlterField(
            model_name='jefe',
            name='telfij',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Teléfono Fijo'),
        ),
        migrations.AlterField(
            model_name='notaria',
            name='cel2',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Celular 2'),
        ),
        migrations.AlterField(
            model_name='notaria',
            name='telfij',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Teléfono Fijo'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='banco',
            field=models.CharField(blank=True, max_length=40, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='efectivo',
            field=models.BooleanField(default=True, verbose_name='Efectivo?'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fec_pago',
            field=models.DateTimeField(blank=True, verbose_name='Fecha Pago'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='foto_vouc',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Foto Voucher'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='observ',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='tramites',
            name='observ',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cel2',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Celular 2'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='fecha_cese',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cese'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ruc',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telfij',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Teléfono Fijo'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='banco',
            field=models.TextField(blank=True, max_length=40, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='observ',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
    ]
