# Generated by Django 4.0.5 on 2022-09-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palapp', '0011_alter_venta_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='banco',
            field=models.TextField(blank=True, default='', max_length=40, null=True, verbose_name='Banco'),
        ),
    ]
