# Generated by Django 4.0.5 on 2022-09-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palapp', '0012_alter_venta_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='condvta',
            field=models.CharField(choices=[('C', 'Contado'), ('B', 'Financiamiento Banco'), ('P', 'FInanciamiento Propio')], default='C', max_length=1, verbose_name='Condición Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nro_cont',
            field=models.TextField(unique=True, verbose_name='Número de Contrato'),
        ),
    ]
